{
  "openapi": "3.0.0",
  "info": {
    "title": "Users & Results REST API",
    "description": "[UPM] MiW User REST API operations",
    "license": {
      "name": "MIT License",
      "url": "https://opensource.org/licenses/MIT"
    },
    "version": "0.1.0"
  },
  "paths": {
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns all users",
        "description": "Returns all users from the system.",
        "operationId": "get_all_users",
        "responses": {
          "200": {
            "description": "User array response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UsersArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Creates a new user",
        "description": "Creates a new user",
        "operationId": "create_user",
        "responses": {
          "201": {
            "description": "`Created` User created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "`Bad Request` Username or email already exists.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          },
          "422": {
            "description": "`Unprocessable entity` Username, e-mail or password is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/UserData"
              }
            }
          },
          "description": "`User` properties to add to the system",
          "required": true
        }
      },
      "options": {
        "tags": [
          "Users"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "options_users",
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deletes all users",
        "description": "Deletes all users ",
        "operationId": "delete_users",
        "responses": {
          "200": {
            "description": "Users deleted"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Returns a user based on a single ID",
        "description": "Returns the user identified by `userId`.",
        "operationId": "get_user_byId",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "User",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Updates a user",
        "description": "Updates the user identified by `userId`.",
        "operationId": "update_user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "202": {
            "description": "`Accepted` User previously existed and is now updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "`Bad Request` User name or e-mail already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          },
          "422": {
            "description": "`Unprocessable entity` Username, e-mail, enabled or password is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserData"
              }
            }
          },
          "description": "`User` data to update",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deletes a user",
        "description": "Deletes the user identified by `userId`.",
        "operationId": "delete_user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "`OK` User deleted"
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "options": {
        "tags": [
          "Users"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "options_userById",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/results": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Returns all results",
        "description": "Returns all results from the system.",
        "operationId": "get_all_results",
        "responses": {
          "200": {
            "description": "Results array response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResultArray"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "post": {
        "tags": [
          "Results"
        ],
        "summary": "Creates a new result",
        "description": "Creates a new result",
        "operationId": "create_result",
        "responses": {
          "201": {
            "description": "`Created` Result created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Result"
                }
              }
            }
          },
          "422": {
            "description": "`Unprocessable entity` Result or user Id is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResultData"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/ResultData"
              }
            }
          },
          "description": "`Result` properties to add to the system",
          "required": true
        }
      },
      "options": {
        "tags": [
          "Results"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "options_results",
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Results"
        ],
        "summary": "Deletes all results",
        "description": "Deletes all results ",
        "operationId": "delete_results",
        "responses": {
          "200": {
            "description": "Results deleted"
          }
        }
      }
    },
    "/results/{id}": {
      "get": {
        "tags": [
          "Results"
        ],
        "summary": "Returns a result based on a single ID",
        "description": "Returns the result identified by `resultId`.",
        "operationId": "get_result_byId",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "Result",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Result"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "put": {
        "tags": [
          "Results"
        ],
        "summary": "Updates a result",
        "description": "Updates the result identified by `resultId`.",
        "operationId": "update_result",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "202": {
            "description": "`Accepted` Result previously existed and is now updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          },
          "422": {
            "description": "`Unprocessable entity` Result or userID is left out",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResultData"
              }
            }
          },
          "description": "`Result` data to update",
          "required": true
        }
      },
      "delete": {
        "tags": [
          "Results"
        ],
        "summary": "Deletes a result",
        "description": "Deletes the result identified by `resultId`.",
        "operationId": "delete_result",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "`OK` Result deleted"
          },
          "404": {
            "$ref": "#/components/responses/404_Resource_Not_Found_Response"
          }
        }
      },
      "options": {
        "tags": [
          "Results"
        ],
        "summary": "Provides the list of HTTP supported methods",
        "description": "Return a `Allow` header with a list of HTTP supported methods.",
        "operationId": "options_resultById",
        "parameters": [
          {
            "$ref": "#/components/parameters/resultId"
          }
        ],
        "responses": {
          "200": {
            "description": "`Allow` header ",
            "headers": {
              "allow": {
                "description": "List of HTTP supported methods",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },

  "tags": [
    {
      "name": "Users",
      "description": "User Administration"
    },
    {
      "name": "Results",
      "description": "Result Administration"
    }
  ],
  "servers": [
    {
      "url": "http://localhost:8000/api/v1"
    },
    {
      "url": "https://localhost:8000/api/v1"
    }
  ],
  "components": {
    "parameters": {
      "userId": {
        "name": "userId",
        "in": "path",
        "description": "ID of user",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      },
      "resultId": {
        "name": "resultId",
        "in": "path",
        "description": "ID of result",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "responses": {
      "401_Unauthorized_Response": {
        "description": "`Unauthorized` invalid `token` header",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/x-yaml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      },
      "403_Forbidden_Response": {
        "description": "`Forbidden` You don't have permission to access",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/x-yaml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      },
      "404_Resource_Not_Found_Response": {
        "description": "`Not found` resource not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          },
          "application/x-yaml": {
            "schema": {
              "$ref": "#/components/schemas/Message"
            }
          }
        }
      }
    },
    "schemas": {
      "User": {
        "required": [
          "id",
          "username",
          "email"
        ],
        "properties": {
          "id": {
            "description": "User Id",
            "type": "integer",
            "format": "int32"
          },
          "username": {
            "description": "User name",
            "type": "string"
          },
          "email": {
            "description": "User email",
            "type": "string"
          },
          "enabled": {
            "description": "Denotes if user is enabled",
            "type": "boolean"
          },
          "isAdmin": {
            "description": "Denotes if user has admin privileges",
            "type": "boolean"
          }
        },
        "example": {
          "user": {
            "id": 1508,
            "username": "User name",
            "email": "User email",
            "enabled": true,
            "admin": false
          }
        }
      },
      "UserData": {
        "properties": {
          "username": {
            "description": "User name",
            "type": "string"
          },
          "email": {
            "description": "User email",
            "type": "string"
          },
          "password": {
            "description": "User password",
            "type": "string",
            "format": "password"
          },
          "enabled": {
            "description": "Denotes if user is enabled",
            "type": "boolean"
          },
          "isAdmin": {
            "description": "Denotes if user has admin privileges",
            "type": "boolean"
          }
        },
        "example": {
          "username": "User_name",
          "email": "User_email@example.com",
          "password": "User_password",
          "enabled": true,
          "isAdmin": false
        }
      },
      "UsersArray": {
        "properties": {
          "users": {
            "description": "Users array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/User"
            }
          }
        }
      },
      "Result": {
        "required": [
          "user",
          "result"
        ],
        "properties": {
          "id": {
            "description": "Result Id",
            "type": "integer",
            "format": "int32"
          },
          "result": {
            "description": "Result value",
            "type": "integer"
          },
          "user": {
            "description": "User object",
            "type": "object"
          },
          "time": {
            "description": "Date time",
            "type": "string"
          }
        },
        "example": {
          "id": 25,
          "result": 500,
          "user": {
            "id": 288,
            "username": "alex",
            "email": "alex@miw.com",
            "enabled": true,
            "admin": false,
            "password": "alexMIW"
          },
          "time": "2018-12-30 21:30:22"
        }
      },
      "ResultData": {
        "required": [
          "user",
          "result"
        ],
        "properties": {
          "result": {
            "description": "Result",
            "type": "integer"
          },
          "user": {
            "description": "User object",
            "type": "object"
          }
        },
        "example": {
          "result": 500,
          "user": {
            "id": 288,
            "username": "alex",
            "email": "alex@miw.com",
            "enabled": true,
            "admin": false,
            "password": "alexMIW"
          }
        }
      },
      "ResultsArray": {
        "properties": {
          "results": {
            "description": "Results array",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Result"
            }
          }
        }
      },
      "Message": {
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "description": "Response code",
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "description": "Response message",
            "type": "string"
          }
        },
        "example": {
          "message": {
            "code": "HTTP code",
            "message": "Response Message"
          }
        }
      }
    }
  }
}